### ISSUE TITLE
Camel metrics JSON serialization throws ClassNotFoundException

### ISSUE THREAD

**Issue by anbeng** [wildfly-extras/wildfly-camel#2366]
Camel metrics not working in release 5.0. 

```
2017-12-14 14:16:23,354 INFO  [org.apache.camel.spring.SpringCamelContext] (MSC service thread 1-2) Apache Camel 2.20.1 (CamelContext: spring-context) is shutdown in 0.007 seconds
2017-12-14 14:16:23,355 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."avs-ws-client.war".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.unit."avs-ws-client.war".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of deployment "avs-ws-client.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:172)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException
	at org.apache.camel.component.metrics.messagehistory.MetricsMessageHistoryFactory.doStart(MetricsMessageHistoryFactory.java:155)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.impl.DefaultCamelContext.doAddService(DefaultCamelContext.java:1495)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1455)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3394)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:208)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3249)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3245)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3268)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3245)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3168)
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:133)
	at org.wildfly.extension.camel.deployment.CamelContextActivationProcessor$1.call(CamelContextActivationProcessor.java:61)
	at org.wildfly.extension.camel.deployment.CamelContextActivationProcessor$1.call(CamelContextActivationProcessor.java:58)
	at org.wildfly.extension.camel.proxy.ProxyUtils$1.invoke(ProxyUtils.java:51)
	at com.sun.proxy.$Proxy196.call(Unknown Source)
	at org.wildfly.extension.camel.proxy.ProxyUtils.invokeProxied(ProxyUtils.java:55)
	at org.wildfly.extension.camel.deployment.CamelContextActivationProcessor.deploy(CamelContextActivationProcessor.java:58)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:165)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException from [Module "org.apache.camel.component.metrics" from local module loader @17d99928 (finder: local module finder @3834d63f (roots: C:\jboss\wildfly-11.0.0.Final\modules,C:\jboss\wildfly-11.0.0.Final\modules\system\layers\fuse,C:\jboss\wildfly-11.0.0.Final\modules\system\layers\base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 26 more

```

In order to fix the issue the following files had to be modified.

Added:

	<module name="com.fasterxml.jackson.core.jackson-core" />

To:

modules\system\layers\fuse\io\dropwizard\metrics\main\module.xml
modules\system\layers\fuse\org\apache\camel\component\metrics\main\module.xml

**Comment by jamesnetherton** [comment]
Thanks for reporting :+1:
